
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 1170833
	#The name of the modpack
	modpackName = "Artemis: Project"
	#The version of the modpack
	modpackVersion = "0.3.2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

