#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 07 01:41:36 CEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=ComplementaryUnbound_r5.9 + EuphoriaPatches_1.10.0
enableShaders=true
