[ammo9mm]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammodefault]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo45acp]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo46]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo357]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo57]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo50ae]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo545]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo556]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo68]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo762]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo762x51]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo338lapua]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo50bmg]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammo12gauge]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammolasercharge]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ammocreative]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[grenade40mm]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[grenade20mm]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[smaw_rocket]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[at4_rocket]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[javelin_rocket]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[grenade]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[m1911a1]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[tti_viper]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[p30l]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[mk23]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[glock17]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[glock18]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[m9]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[deserteagle]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 10.0

[rhino]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 10.0

[m4a1]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[m4a1mod1]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[ar57]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 4.0

[ro635]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[star15]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 8.0

[m4sopmodii]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[m16a1]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[hk416]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[scarl]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[xm7]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 6.5

[xm29]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[g36c]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[g36k]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[sl8]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 9.0

[mk14ebr]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 9.0

[uar10]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 15.0

[ak47]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 7.0

[ak74]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 6.0

[ak12]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 6.0

[an94]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 6.0

[aug]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[aughbar]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[mp5]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[mp7]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 4.0

[ump45]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 4.0

[vector]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[p90]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[tmp]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 3.5

[m950]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[g41]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[g3]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 9.0

[wa2000]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 22.0

[xm3]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 25.0

[c14]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 25.0

[l96a1]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 28.0

[ballista]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 28.0

[gm6lynx]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 35.0

[m590]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 2.200000047683716

[m870]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.899999976158142

[spas12]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[m1014]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.2000000476837158

[aa12]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.0

[citoricxs]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.5

[hs12]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 1.5

[lamg]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[mk48]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 7.0

[m249]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[m32mgl]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[smaw]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[javelin]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[at4]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

[m134minigun]
#Set to `false` to remove the item from the game.
enabled = true
#Sets this item damage.
#Range: 0.01 ~ 100.0
damage = 5.0

